Console.WriteLine("Введите Х точки А ");
int ax;
ax = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите У точки А  ");
int ay;
ay = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите Z точки A  ");
int az;
az = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите Х точки В ");
int bx;
bx = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите У точки В  ");
int by;
by = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите Z точки В  ");
int bz;
bz = Convert.ToInt32(Console.ReadLine());
double result = Math.Sqrt((ax - bx) * (ax - bx) + (ay - by) * (ay - by) + (az - bz) * (az - bz)); 
double resultRound = Math.Round(result, 2); 
Console.WriteLine($" AB = {resultRound}");
